services:
  # Background worker for the main bot
  - type: worker
    name: autowork-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python cron_monitor.py"
    envVars:
      - key: FREELANCER_OAUTH_TOKEN
        sync: false  # This means you need to set it manually in Render dashboard
      - key: FREELANCER_USER_ID
        value: "45214417"
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: PYTHONUNBUFFERED
        value: "1"  # Ensures logs are shown immediately
      - key: TZ
        value: "UTC"  # Timezone